#Not being used anymore as the host level nginx is used now for routing on VM
version: '3'
services:
  nginx:
    image: revoly/portfolio
    ports:
      - 80:80
      - 443:443
    volumes:
      - /etc/nginx/certs:/etc/nginx/certs