# Use an official Nginx image as the base image
FROM nginx:latest

# Copy the contents of the public directory to the Nginx web root directory
COPY public /usr/share/nginx/html

# Expose port 80 for Nginx
EXPOSE 80
