name: CI Pipeline

on: 
  push: 
    branches:
      - master



jobs:
  build-portfolio:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Transpile typescript to Javascript and build
        uses: actions/setup-node@v1
        with:
          node-version: '12.2.0'
      - run: node -v 
      - run: npm install
      - run: npm run build

      - name: Build the image and push to docker hub.
        run: |
            docker build . -t revoly/portfolio
            docker login -u revoly -p ${{ secrets.DOCKER_PASS}} 
            docker push revoly/portfolio
            docker logout
      - name: Run deploy script on the server
        uses: appleboy/ssh-action@master
        with:
          host: revoly.dev
          username: root
          passphrase: ${{ secrets.PASS_PHRASE }}
          key: ${{ secrets.KEY }}
          script: ~/restart.sh 
  build-blog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with: 
          submodules: true
      - name: Build hugo
        run: cd blogs/blog;sudo apt install hugo; hugo
      - name: Build the image and push to docker hub.
        run: |
            cd blogs;blog
            docker build . -t revoly/blog
            docker login -u revoly -p ${{ secrets.DOCKER_PASS}} 
            docker push revoly/blog
            docker logout
      - name: Run deploy script on the server
        uses: appleboy/ssh-action@master
        with:
          host: revoly.dev
          username: root
          passphrase: ${{ secrets.PASS_PHRASE }}
          key: ${{ secrets.KEY }}
          script: ~/restart.sh #TODO: Split this script 
